// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TailBuddys.Infrastructure.Data;

#nullable disable

namespace TailBuddys.Infrastructure.Migrations
{
    [DbContext(typeof(TailBuddysContext))]
    [Migration("20250422100033_InitialwithSeed")]
    partial class InitialwithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogParks", b =>
                {
                    b.Property<int>("DogLikesId")
                        .HasColumnType("int");

                    b.Property<int>("FavParksId")
                        .HasColumnType("int");

                    b.HasKey("DogLikesId", "FavParksId");

                    b.HasIndex("FavParksId");

                    b.ToTable("DogParks", (string)null);

                    b.HasData(
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 14
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 14
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 21
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 21
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 6
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 18
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId", "ReceiverDogId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("ChatNotifications");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vaccinated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "189 Yitzhak Rabin St, Rehovot",
                            BirthDate = new DateTime(2020, 6, 30, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Sasha.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.02279791006703,
                            Lon = 35.02987148102909,
                            Name = "Winnie",
                            Size = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 1,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "168 HaShalom St, Netanya",
                            BirthDate = new DateTime(2024, 6, 12, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Buddy.",
                            Gender = true,
                            IsBot = false,
                            Lat = 32.093257450271622,
                            Lon = 35.22312043159193,
                            Name = "Zeus",
                            Size = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 2,
                            Vaccinated = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "160 Jabotinsky St, Tel Aviv",
                            BirthDate = new DateTime(2015, 6, 7, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Simba.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.439248811254867,
                            Lon = 35.270164751878944,
                            Name = "Finn",
                            Size = 2,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 3,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 4,
                            Address = "50 Jabotinsky St, Haifa",
                            BirthDate = new DateTime(2022, 9, 12, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Charlie.",
                            Gender = true,
                            IsBot = false,
                            Lat = 29.769791740361303,
                            Lon = 35.036427089186418,
                            Name = "Scout",
                            Size = 0,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 4,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 5,
                            Address = "180 Herzl St, Netanya",
                            BirthDate = new DateTime(2015, 7, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Sam.",
                            Gender = false,
                            IsBot = false,
                            Lat = 32.614064428945873,
                            Lon = 35.079831776756521,
                            Name = "Daisy",
                            Size = 2,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 5,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 6,
                            Address = "46 Hagana St, Ramat Gan",
                            BirthDate = new DateTime(2018, 6, 15, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Ellie.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.33084872652989,
                            Lon = 34.985237149380509,
                            Name = "Winnie",
                            Size = 1,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 6,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 7,
                            Address = "132 Rothschild St, Ashkelon",
                            BirthDate = new DateTime(2024, 12, 14, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Zoe.",
                            Gender = false,
                            IsBot = true,
                            Lat = 31.528470989993522,
                            Lon = 35.181771288619828,
                            Name = "Scout",
                            Size = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 7,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 8,
                            Address = "119 Dizengoff St, Bat Yam",
                            BirthDate = new DateTime(2018, 11, 12, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Honey.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.416631747446072,
                            Lon = 34.857384171298129,
                            Name = "Milo",
                            Size = 2,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 8,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 9,
                            Address = "123 Herzl St, Nazareth",
                            BirthDate = new DateTime(2018, 12, 8, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Rex.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.173593726202309,
                            Lon = 35.416953542718105,
                            Name = "Rocky",
                            Size = 0,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 9,
                            Vaccinated = false
                        },
                        new
                        {
                            Id = 10,
                            Address = "125 Aharonovitch St, Holon",
                            BirthDate = new DateTime(2016, 9, 21, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Sam.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.871736483158717,
                            Lon = 35.062910036536323,
                            Name = "Jasper",
                            Size = 2,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 10,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 11,
                            Address = "191 Weizmann St, Beit Shemesh",
                            BirthDate = new DateTime(2024, 8, 9, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Ginger.",
                            Gender = false,
                            IsBot = false,
                            Lat = 32.450180042761097,
                            Lon = 35.021175391052559,
                            Name = "Sadie",
                            Size = 1,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 11,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 12,
                            Address = "24 Menachem Begin St, Ashdod",
                            BirthDate = new DateTime(2024, 12, 3, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Stella.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.511282098675814,
                            Lon = 35.029709564979107,
                            Name = "Nova",
                            Size = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 12,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 13,
                            Address = "197 Rothschild St, Holon",
                            BirthDate = new DateTime(2022, 8, 12, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Scout.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.214464759719434,
                            Lon = 35.098992632889882,
                            Name = "Ginger",
                            Size = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 13,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 14,
                            Address = "132 Rothschild St, Ashkelon",
                            BirthDate = new DateTime(2018, 6, 14, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Sky.",
                            Gender = true,
                            IsBot = false,
                            Lat = 29.734861955524391,
                            Lon = 34.979740385488135,
                            Name = "Winnie",
                            Size = 2,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 14,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 15,
                            Address = "22 Dizengoff St, Nazareth",
                            BirthDate = new DateTime(2023, 8, 8, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Jack.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.23051891452225,
                            Lon = 34.935224973524697,
                            Name = "Zoe",
                            Size = 0,
                            Type = 7,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 15,
                            Vaccinated = false
                        },
                        new
                        {
                            Id = 16,
                            Address = "176 Arlozorov St, Petah Tikva",
                            BirthDate = new DateTime(2017, 11, 27, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Ellie.",
                            Gender = true,
                            IsBot = true,
                            Lat = 31.136925642725611,
                            Lon = 35.437282351581572,
                            Name = "Moose",
                            Size = 1,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 16,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 17,
                            Address = "73 Aharonovitch St, Haifa",
                            BirthDate = new DateTime(2016, 7, 25, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Hazel.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.423585718571452,
                            Lon = 35.337085756541555,
                            Name = "Shadow",
                            Size = 0,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 17,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 18,
                            Address = "97 Menachem Begin St, Tel Aviv",
                            BirthDate = new DateTime(2020, 1, 31, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Zeus.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.227313805742241,
                            Lon = 34.970613551189402,
                            Name = "Ace",
                            Size = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 18,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 19,
                            Address = "168 Weizmann St, Eilat",
                            BirthDate = new DateTime(2018, 2, 15, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Sadie.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.741889956955568,
                            Lon = 34.982610135697314,
                            Name = "Zoe",
                            Size = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 19,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 20,
                            Address = "116 Menachem Begin St, Tiberias",
                            BirthDate = new DateTime(2021, 11, 4, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Friendly dog that loves Riley.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.926854770870573,
                            Lon = 35.420202352205116,
                            Name = "Honey",
                            Size = 2,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            UserId = 20,
                            Vaccinated = true
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("ParkId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "189 Weizmann St, Nazareth",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.069288199804017,
                            Lon = 35.006777362417019,
                            Name = "Gan Meir",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 2,
                            Address = "163 Allenby St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.448240338888613,
                            Lon = 35.364853386938968,
                            Name = "Independence Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 3,
                            Address = "190 Herzl St, Petah Tikva",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.812748478983007,
                            Lon = 34.727004137170169,
                            Name = "Yarkon Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 4,
                            Address = "51 Allenby St, Tiberias",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.7936932256139,
                            Lon = 34.986387987444147,
                            Name = "Sacher Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 5,
                            Address = "191 Allenby St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.108591891694548,
                            Lon = 34.888822867770372,
                            Name = "Ramat Gan National Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 6,
                            Address = "185 King David St, Netanya",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.615555265448442,
                            Lon = 35.136573526678433,
                            Name = "HaPisga Garden",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 7,
                            Address = "199 Herzl St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.722862846798083,
                            Lon = 34.743257869342393,
                            Name = "Canada Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 8,
                            Address = "30 Arlozorov St, Hadera",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.143078813719718,
                            Lon = 35.15004255689999,
                            Name = "Ashdod Yam Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 9,
                            Address = "199 Herzl St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.274865492626304,
                            Lon = 35.16566064029945,
                            Name = "Gan Ha'ir",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 10,
                            Address = "81 Allenby St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.946315971567543,
                            Lon = 35.441871702704418,
                            Name = "Armon Hanatziv Promenade",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 11,
                            Address = "105 Arlozorov St, Netanya",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.737274504275049,
                            Lon = 35.097497530130781,
                            Name = "Liberty Bell Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 12,
                            Address = "176 Ben Gurion St, Jerusalem",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.307368999281589,
                            Lon = 34.872268925268919,
                            Name = "Lachish Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 13,
                            Address = "104 King David St, Beer Sheva",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.167718978764498,
                            Lon = 35.167208075036285,
                            Name = "Ariel Sharon Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 14,
                            Address = "184 Ben Gurion St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.182260782860055,
                            Lon = 35.009898771449514,
                            Name = "Park Giv'atayim",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 15,
                            Address = "65 HaShalom St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 29.609916306640887,
                            Lon = 34.862890909036736,
                            Name = "Herzliya Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 16,
                            Address = "183 Arlozorov St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.705701722316231,
                            Lon = 35.249727008082751,
                            Name = "Park Ashkelon",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 17,
                            Address = "119 Aharonovitch St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.947423513694464,
                            Lon = 35.239549960849367,
                            Name = "Beit She'an Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 18,
                            Address = "121 Herzl St, Ashkelon",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.389314457882712,
                            Lon = 35.07870247788226,
                            Name = "Ein Gedi Reserve",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 19,
                            Address = "130 HaPalmach St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.736471099589998,
                            Lon = 34.884448424899659,
                            Name = "Neot Kedumim",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 20,
                            Address = "17 Arlozorov St, Ashkelon",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.178892991237337,
                            Lon = 35.359587515227872,
                            Name = "Ma'ayan Harod",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 21,
                            Address = "151 Herzl St, Bat Yam",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.193899603054195,
                            Lon = 35.379169792680067,
                            Name = "Timna Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 22,
                            Address = "163 Allenby St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 29.940032466542284,
                            Lon = 34.904774858082376,
                            Name = "Alona Park",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 23,
                            Address = "188 Jabotinsky St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.740292443118594,
                            Lon = 35.325978076515696,
                            Name = "Park Kiryat Motzkin",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 24,
                            Address = "184 Ben Gurion St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.886822260235405,
                            Lon = 34.918373244149777,
                            Name = "Bat Galim Promenade",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2004, 3, 2, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9890),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user1@tail.com",
                            FirstName = "User1",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last1",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1986, 3, 11, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9924),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user2@tail.com",
                            FirstName = "User2",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last2",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2008, 1, 24, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9930),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user3@tail.com",
                            FirstName = "User3",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last3",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2004, 6, 13, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9937),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user4@tail.com",
                            FirstName = "User4",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last4",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 10, 15, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9944),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user5@tail.com",
                            FirstName = "User5",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last5",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1976, 10, 18, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9951),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user6@tail.com",
                            FirstName = "User6",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last6",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1984, 7, 5, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9958),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user7@tail.com",
                            FirstName = "User7",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last7",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1993, 7, 20, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9965),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user8@tail.com",
                            FirstName = "User8",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last8",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1983, 4, 17, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9972),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user9@tail.com",
                            FirstName = "User9",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last9",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1977, 11, 10, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(9980),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user10@tail.com",
                            FirstName = "User10",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last10",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1996, 9, 18, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(79),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user11@tail.com",
                            FirstName = "User11",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last11",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1990, 10, 16, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(86),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user12@tail.com",
                            FirstName = "User12",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last12",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2004, 7, 24, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(94),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user13@tail.com",
                            FirstName = "User13",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last13",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1995, 8, 3, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(102),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user14@tail.com",
                            FirstName = "User14",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last14",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1994, 9, 29, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(108),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user15@tail.com",
                            FirstName = "User15",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last15",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1989, 11, 7, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(114),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user16@tail.com",
                            FirstName = "User16",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last16",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1982, 12, 1, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(121),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user17@tail.com",
                            FirstName = "User17",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last17",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2002, 11, 16, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(127),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user18@tail.com",
                            FirstName = "User18",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last18",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1985, 7, 10, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(133),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user19@tail.com",
                            FirstName = "User19",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last19",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1998, 9, 30, 10, 0, 32, 113, DateTimeKind.Utc).AddTicks(140),
                            CreatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714),
                            Email = "user20@tail.com",
                            FirstName = "User20",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last20",
                            UpdatedAt = new DateTime(2025, 4, 22, 10, 0, 32, 112, DateTimeKind.Utc).AddTicks(8714)
                        });
                });

            modelBuilder.Entity("DogParks", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Park", null)
                        .WithMany()
                        .HasForeignKey("FavParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("ChatsAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("ChatsAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("UnreadChatNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("Images")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TailBuddys.Core.Models.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dog");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("MatchesAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("MatchesAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("MatchNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Match", "Match")
                        .WithMany("MatchNotification")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Navigation("ChatsAsReceiver");

                    b.Navigation("ChatsAsSender");

                    b.Navigation("Images");

                    b.Navigation("MatchNotification");

                    b.Navigation("MatchesAsReceiver");

                    b.Navigation("MatchesAsSender");

                    b.Navigation("UnreadChatNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Navigation("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
