// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TailBuddys.Infrastructure.Data;

#nullable disable

namespace TailBuddys.Infrastructure.Migrations
{
    [DbContext(typeof(TailBuddysContext))]
    [Migration("20250423100103_InitialwithSeed")]
    partial class InitialwithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogParks", b =>
                {
                    b.Property<int>("DogLikesId")
                        .HasColumnType("int");

                    b.Property<int>("FavParksId")
                        .HasColumnType("int");

                    b.HasKey("DogLikesId", "FavParksId");

                    b.HasIndex("FavParksId");

                    b.ToTable("DogParks", (string)null);

                    b.HasData(
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 6
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 6
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 22
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 14
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 16
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ReceiverDogArchive")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<bool>("SenderDogArchive")
                        .HasColumnType("bit");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId", "ReceiverDogId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("ChatNotifications");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vaccinated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "61 Jabotinsky St, Modiin",
                            BirthDate = new DateTime(2018, 6, 3, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Lola.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.640431199876161,
                            Lon = 35.408581198529077,
                            Name = "Olive",
                            Size = 1,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 1,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "133 Hagana St, Hadera",
                            BirthDate = new DateTime(2019, 11, 27, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Sadie.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.733736929248877,
                            Lon = 34.708256827775905,
                            Name = "Stella",
                            Size = 1,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 2,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "110 Rothschild St, Jerusalem",
                            BirthDate = new DateTime(2018, 8, 29, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Lola.",
                            Gender = true,
                            IsBot = false,
                            Lat = 32.146585539432763,
                            Lon = 35.046480338148854,
                            Name = "Ace",
                            Size = 2,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 3,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 4,
                            Address = "159 King David St, Ashkelon",
                            BirthDate = new DateTime(2016, 1, 10, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Leo.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.058638490468521,
                            Lon = 34.796184218521375,
                            Name = "Sadie",
                            Size = 1,
                            Type = 7,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 4,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 5,
                            Address = "133 Yitzhak Rabin St, Eilat",
                            BirthDate = new DateTime(2024, 11, 8, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Luna.",
                            Gender = false,
                            IsBot = true,
                            Lat = 31.387292768760137,
                            Lon = 34.842299004318001,
                            Name = "Jack",
                            Size = 1,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 5,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 6,
                            Address = "133 Yitzhak Rabin St, Eilat",
                            BirthDate = new DateTime(2019, 10, 10, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Hazel.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.091991952509723,
                            Lon = 35.168837978949121,
                            Name = "Lucky",
                            Size = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 6,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 7,
                            Address = "182 Menachem Begin St, Tel Aviv",
                            BirthDate = new DateTime(2016, 1, 19, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Buddy.",
                            Gender = true,
                            IsBot = false,
                            Lat = 29.858077914402024,
                            Lon = 34.942563039231899,
                            Name = "Max",
                            Size = 2,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 7,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 8,
                            Address = "179 Hagana St, Petah Tikva",
                            BirthDate = new DateTime(2018, 12, 7, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Rosie.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.776591754499869,
                            Lon = 35.06003130659569,
                            Name = "Otis",
                            Size = 2,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 8,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 9,
                            Address = "159 King David St, Ashkelon",
                            BirthDate = new DateTime(2021, 11, 16, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Rex.",
                            Gender = true,
                            IsBot = true,
                            Lat = 31.783936653365281,
                            Lon = 35.137342901173454,
                            Name = "Pepper",
                            Size = 1,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 9,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 10,
                            Address = "110 Rothschild St, Jerusalem",
                            BirthDate = new DateTime(2018, 2, 2, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Jack.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.839718508472352,
                            Lon = 35.381299113049742,
                            Name = "Stella",
                            Size = 0,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 10,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 11,
                            Address = "26 HaPalmach St, Beit Shemesh",
                            BirthDate = new DateTime(2021, 7, 26, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Nova.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.218509017174636,
                            Lon = 34.833884672433157,
                            Name = "Gracie",
                            Size = 1,
                            Type = 7,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 11,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 12,
                            Address = "189 HaPalmach St, Beit Shemesh",
                            BirthDate = new DateTime(2019, 11, 9, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Benji.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.078484771090253,
                            Lon = 35.203869910512211,
                            Name = "Bella",
                            Size = 1,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 12,
                            Vaccinated = false
                        },
                        new
                        {
                            Id = 13,
                            Address = "150 Allenby St, Modiin",
                            BirthDate = new DateTime(2016, 10, 5, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Harley.",
                            Gender = false,
                            IsBot = false,
                            Lat = 32.467574562400195,
                            Lon = 34.982222104068214,
                            Name = "Stella",
                            Size = 2,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 13,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 14,
                            Address = "109 Yitzhak Rabin St, Ashdod",
                            BirthDate = new DateTime(2021, 2, 20, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Sky.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.757461654958824,
                            Lon = 34.970683634830586,
                            Name = "Luna",
                            Size = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 14,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 15,
                            Address = "68 Jabotinsky St, Kiryat Gat",
                            BirthDate = new DateTime(2022, 1, 12, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Sky.",
                            Gender = true,
                            IsBot = true,
                            Lat = 31.207649239441132,
                            Lon = 35.105008693338988,
                            Name = "Jasper",
                            Size = 0,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 15,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 16,
                            Address = "31 Arlozorov St, Petah Tikva",
                            BirthDate = new DateTime(2018, 8, 11, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Otis.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.369541918154951,
                            Lon = 35.276504067777871,
                            Name = "Marley",
                            Size = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 16,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 17,
                            Address = "159 Menachem Begin St, Modiin",
                            BirthDate = new DateTime(2020, 2, 18, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Benji.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.966179520031542,
                            Lon = 35.196761291569487,
                            Name = "Lucky",
                            Size = 1,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 17,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 18,
                            Address = "144 Ben Gurion St, Hadera",
                            BirthDate = new DateTime(2022, 10, 29, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Rex.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.799090133364668,
                            Lon = 35.201983595944526,
                            Name = "Lucky",
                            Size = 2,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 18,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 19,
                            Address = "95 King David St, Tiberias",
                            BirthDate = new DateTime(2024, 11, 5, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Sasha.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.688498091576513,
                            Lon = 35.357313938839276,
                            Name = "Sasha",
                            Size = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 19,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 20,
                            Address = "151 King David St, Hadera",
                            BirthDate = new DateTime(2016, 5, 16, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Friendly dog that loves Lucy.",
                            Gender = true,
                            IsBot = false,
                            Lat = 32.830731840275625,
                            Lon = 34.946591203507509,
                            Name = "Rocky",
                            Size = 0,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            UserId = 20,
                            Vaccinated = true
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("ParkId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "74 Herzl St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.803725685895337,
                            Lon = 35.08125940049338,
                            Name = "Gan Meir",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 2,
                            Address = "72 Hagana St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.725036064898752,
                            Lon = 34.954051845419912,
                            Name = "Independence Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 3,
                            Address = "22 Aharonovitch St, Herzliya",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.005056765930959,
                            Lon = 35.047166356555692,
                            Name = "Yarkon Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 4,
                            Address = "135 Menachem Begin St, Bat Yam",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.16620074472419,
                            Lon = 34.737777651569608,
                            Name = "Sacher Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 5,
                            Address = "164 Weizmann St, Ashdod",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.195625805117935,
                            Lon = 34.996128479064353,
                            Name = "Ramat Gan National Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 6,
                            Address = "151 Dizengoff St, Nazareth",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.958522208954417,
                            Lon = 34.758238393754027,
                            Name = "HaPisga Garden",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 7,
                            Address = "151 Dizengoff St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.288782473028167,
                            Lon = 34.834898922475631,
                            Name = "Canada Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 8,
                            Address = "151 Dizengoff St, Nazareth",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.242960511823114,
                            Lon = 35.154823685046118,
                            Name = "Ashdod Yam Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 9,
                            Address = "164 Menachem Begin St, Petah Tikva",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.455896755262145,
                            Lon = 35.093623190359494,
                            Name = "Gan Ha'ir",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 10,
                            Address = "26 Weizmann St, Herzliya",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.327378026598232,
                            Lon = 35.017367928682944,
                            Name = "Armon Hanatziv Promenade",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 11,
                            Address = "91 Ben Gurion St, Ashkelon",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.956513248467385,
                            Lon = 35.044852696683627,
                            Name = "Liberty Bell Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 12,
                            Address = "13 Hagana St, Holon",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 29.893493371060131,
                            Lon = 35.072434110942233,
                            Name = "Lachish Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 13,
                            Address = "59 Menachem Begin St, Ashkelon",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.690470323125162,
                            Lon = 35.189430963909892,
                            Name = "Ariel Sharon Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 14,
                            Address = "189 HaPalmach St, Netanya",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.077056006116386,
                            Lon = 34.845375654818014,
                            Name = "Park Giv'atayim",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 15,
                            Address = "140 Weizmann St, Tel Aviv",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.287636410949133,
                            Lon = 35.058807202618212,
                            Name = "Herzliya Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 16,
                            Address = "165 Herzl St, Hadera",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.942294456861362,
                            Lon = 35.282088308709355,
                            Name = "Park Ashkelon",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 17,
                            Address = "23 Aharonovitch St, Tel Aviv",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.995432802309619,
                            Lon = 35.237696523311882,
                            Name = "Beit She'an Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 18,
                            Address = "13 Hagana St, Holon",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.562650586009166,
                            Lon = 34.837084187746015,
                            Name = "Ein Gedi Reserve",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 19,
                            Address = "92 Dizengoff St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.907255533165753,
                            Lon = 35.14256578911349,
                            Name = "Neot Kedumim",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 20,
                            Address = "86 Hagana St, Herzliya",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.135416503603089,
                            Lon = 35.271950058982455,
                            Name = "Ma'ayan Harod",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 21,
                            Address = "133 HaPalmach St, Netanya",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.153804826036271,
                            Lon = 35.429314614064118,
                            Name = "Timna Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 22,
                            Address = "72 Hagana St, Beit Shemesh",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.199151251395598,
                            Lon = 34.935912882533579,
                            Name = "Alona Park",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 23,
                            Address = "74 Herzl St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.186424658443141,
                            Lon = 34.929330163957317,
                            Name = "Park Kiryat Motzkin",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 24,
                            Address = "181 Herzl St, Bat Yam",
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.57833704702006,
                            Lon = 35.360322825455178,
                            Name = "Bat Galim Promenade",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2004, 7, 7, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1953),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user1@tail.com",
                            FirstName = "User1",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last1",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2002, 5, 6, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1973),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user2@tail.com",
                            FirstName = "User2",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last2",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1979, 6, 26, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1978),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user3@tail.com",
                            FirstName = "User3",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last3",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2001, 11, 25, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1981),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user4@tail.com",
                            FirstName = "User4",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last4",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1986, 12, 11, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1984),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user5@tail.com",
                            FirstName = "User5",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last5",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1981, 5, 7, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1988),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user6@tail.com",
                            FirstName = "User6",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last6",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1992, 12, 15, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1991),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user7@tail.com",
                            FirstName = "User7",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last7",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2007, 5, 1, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1993),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user8@tail.com",
                            FirstName = "User8",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last8",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2001, 9, 22, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1997),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user9@tail.com",
                            FirstName = "User9",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last9",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1982, 12, 21, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2000),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user10@tail.com",
                            FirstName = "User10",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last10",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1984, 6, 10, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2003),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user11@tail.com",
                            FirstName = "User11",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last11",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1983, 5, 19, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2005),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user12@tail.com",
                            FirstName = "User12",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last12",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1976, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2008),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user13@tail.com",
                            FirstName = "User13",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last13",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2003, 3, 18, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2011),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user14@tail.com",
                            FirstName = "User14",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last14",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1991, 7, 2, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2013),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user15@tail.com",
                            FirstName = "User15",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last15",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1996, 6, 26, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2017),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user16@tail.com",
                            FirstName = "User16",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last16",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1985, 1, 14, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2019),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user17@tail.com",
                            FirstName = "User17",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last17",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2000, 11, 26, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2065),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user18@tail.com",
                            FirstName = "User18",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last18",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2001, 12, 4, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2070),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user19@tail.com",
                            FirstName = "User19",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last19",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1979, 12, 14, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(2074),
                            CreatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457),
                            Email = "user20@tail.com",
                            FirstName = "User20",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last20",
                            UpdatedAt = new DateTime(2025, 4, 23, 10, 1, 2, 643, DateTimeKind.Utc).AddTicks(1457)
                        });
                });

            modelBuilder.Entity("DogParks", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Park", null)
                        .WithMany()
                        .HasForeignKey("FavParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("ChatsAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("ChatsAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("UnreadChatNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("Images")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TailBuddys.Core.Models.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dog");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("MatchesAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("MatchesAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("MatchNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Match", "Match")
                        .WithMany("MatchNotification")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Navigation("ChatsAsReceiver");

                    b.Navigation("ChatsAsSender");

                    b.Navigation("Images");

                    b.Navigation("MatchNotification");

                    b.Navigation("MatchesAsReceiver");

                    b.Navigation("MatchesAsSender");

                    b.Navigation("UnreadChatNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Navigation("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
