// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TailBuddys.Infrastructure.Data;

#nullable disable

namespace TailBuddys.InfraStructure.Migrations
{
    [DbContext(typeof(TailBuddysContext))]
    [Migration("20250420210001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogParks", b =>
                {
                    b.Property<int>("DogLikesId")
                        .HasColumnType("int");

                    b.Property<int>("FavParksId")
                        .HasColumnType("int");

                    b.HasKey("DogLikesId", "FavParksId");

                    b.HasIndex("FavParksId");

                    b.ToTable("DogParks", (string)null);

                    b.HasData(
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 1,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 2,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 3,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 4,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 5,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 12
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 6,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 7,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 8,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 9,
                            FavParksId = 14
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 10,
                            FavParksId = 20
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 21
                        },
                        new
                        {
                            DogLikesId = 11,
                            FavParksId = 7
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 6
                        },
                        new
                        {
                            DogLikesId = 12,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 6
                        },
                        new
                        {
                            DogLikesId = 13,
                            FavParksId = 8
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 13
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 14,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 19
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 15,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 10
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 16,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 18
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 15
                        },
                        new
                        {
                            DogLikesId = 17,
                            FavParksId = 11
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 2
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 16
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 1
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 3
                        },
                        new
                        {
                            DogLikesId = 18,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 5
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 24
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 14
                        },
                        new
                        {
                            DogLikesId = 19,
                            FavParksId = 23
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 17
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 9
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 4
                        },
                        new
                        {
                            DogLikesId = 20,
                            FavParksId = 6
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId", "ReceiverDogId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("ChatNotifications");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vaccinated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "96 Weizmann St, Tel Aviv",
                            BirthDate = new DateTime(2018, 6, 8, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Bailey.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.566440371077096,
                            Lon = 35.225679022790075,
                            Name = "Luna",
                            Size = 2,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 1,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "71 Weizmann St, Herzliya",
                            BirthDate = new DateTime(2021, 5, 5, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Bear.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.659962975647012,
                            Lon = 35.371721538103081,
                            Name = "Rocky",
                            Size = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 2,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "21 Jabotinsky St, Netanya",
                            BirthDate = new DateTime(2023, 12, 6, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Simba.",
                            Gender = false,
                            IsBot = false,
                            Lat = 30.422384858684513,
                            Lon = 35.209225918098838,
                            Name = "Stella",
                            Size = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 3,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 4,
                            Address = "28 HaShalom St, Tiberias",
                            BirthDate = new DateTime(2019, 11, 19, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Max.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.632695831361914,
                            Lon = 35.062451626503737,
                            Name = "Ace",
                            Size = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 4,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 5,
                            Address = "79 Dizengoff St, Kiryat Gat",
                            BirthDate = new DateTime(2019, 1, 7, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Riley.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.961314699576153,
                            Lon = 34.925050460820962,
                            Name = "Leo",
                            Size = 2,
                            Type = 8,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 5,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 6,
                            Address = "71 Weizmann St, Herzliya",
                            BirthDate = new DateTime(2016, 1, 30, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Sky.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.722912895466884,
                            Lon = 35.409144961580985,
                            Name = "Simba",
                            Size = 1,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 6,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 7,
                            Address = "98 Ben Gurion St, Tel Aviv",
                            BirthDate = new DateTime(2022, 4, 26, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Lola.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.109416453022387,
                            Lon = 35.18396518423566,
                            Name = "Maggie",
                            Size = 2,
                            Type = 6,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 7,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 8,
                            Address = "68 Arlozorov St, Rehovot",
                            BirthDate = new DateTime(2016, 2, 2, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Ace.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.519948026808919,
                            Lon = 34.88347919105874,
                            Name = "Milo",
                            Size = 1,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 8,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 9,
                            Address = "142 Hagana St, Modiin",
                            BirthDate = new DateTime(2024, 9, 19, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Buddy.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.387641135306101,
                            Lon = 34.956993994464618,
                            Name = "Rex",
                            Size = 2,
                            Type = 7,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 9,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 10,
                            Address = "199 Herzl St, Jerusalem",
                            BirthDate = new DateTime(2016, 1, 9, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Remy.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.858240736569762,
                            Lon = 35.335335086066394,
                            Name = "Zoe",
                            Size = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 10,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 11,
                            Address = "24 King David St, Ashdod",
                            BirthDate = new DateTime(2017, 5, 25, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Sam.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.8932429816882,
                            Lon = 35.430190032090458,
                            Name = "Zeus",
                            Size = 2,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 11,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 12,
                            Address = "26 Menachem Begin St, Beer Sheva",
                            BirthDate = new DateTime(2021, 9, 30, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Olive.",
                            Gender = false,
                            IsBot = true,
                            Lat = 30.009125122613781,
                            Lon = 34.918384120996592,
                            Name = "Abby",
                            Size = 1,
                            Type = 9,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 12,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 13,
                            Address = "189 King David St, Jerusalem",
                            BirthDate = new DateTime(2015, 9, 8, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Bella.",
                            Gender = false,
                            IsBot = false,
                            Lat = 31.1314256199373,
                            Lon = 35.331789054662913,
                            Name = "Lola",
                            Size = 1,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 13,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 14,
                            Address = "151 Menachem Begin St, Modiin",
                            BirthDate = new DateTime(2024, 2, 3, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Hazel.",
                            Gender = true,
                            IsBot = false,
                            Lat = 32.69701346257051,
                            Lon = 35.09081227731204,
                            Name = "Otis",
                            Size = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 14,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 15,
                            Address = "91 Allenby St, Bat Yam",
                            BirthDate = new DateTime(2018, 9, 23, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Duke.",
                            Gender = true,
                            IsBot = false,
                            Lat = 31.293367298761193,
                            Lon = 35.211767744618413,
                            Name = "Otis",
                            Size = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 15,
                            Vaccinated = false
                        },
                        new
                        {
                            Id = 16,
                            Address = "41 HaPalmach St, Petah Tikva",
                            BirthDate = new DateTime(2018, 8, 16, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Chloe.",
                            Gender = true,
                            IsBot = true,
                            Lat = 32.406461550472223,
                            Lon = 35.198519788357629,
                            Name = "Bella",
                            Size = 0,
                            Type = 7,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 16,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 17,
                            Address = "46 HaShalom St, Tel Aviv",
                            BirthDate = new DateTime(2016, 10, 14, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Olive.",
                            Gender = false,
                            IsBot = false,
                            Lat = 33.083972273857192,
                            Lon = 35.080671430239732,
                            Name = "Ace",
                            Size = 0,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 17,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 18,
                            Address = "11 Allenby St, Holon",
                            BirthDate = new DateTime(2019, 5, 2, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Oscar.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.888385801696185,
                            Lon = 34.805754519785623,
                            Name = "Maple",
                            Size = 0,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 18,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 19,
                            Address = "159 Jabotinsky St, Bat Yam",
                            BirthDate = new DateTime(2016, 10, 13, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Bella.",
                            Gender = true,
                            IsBot = false,
                            Lat = 30.193907286324542,
                            Lon = 34.803433222074133,
                            Name = "Finn",
                            Size = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 19,
                            Vaccinated = true
                        },
                        new
                        {
                            Id = 20,
                            Address = "37 Aharonovitch St, Tiberias",
                            BirthDate = new DateTime(2024, 7, 16, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Friendly dog that loves Rex.",
                            Gender = false,
                            IsBot = false,
                            Lat = 32.171510688353465,
                            Lon = 35.134505482303204,
                            Name = "Charlie",
                            Size = 0,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            UserId = 20,
                            Vaccinated = true
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("ParkId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverDogId")
                        .HasColumnType("int");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverDogId");

                    b.HasIndex("SenderDogId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "159 Arlozorov St, Tiberias",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.932322195059527,
                            Lon = 34.916609376410968,
                            Name = "Gan Meir",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 2,
                            Address = "72 Allenby St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.507919494728601,
                            Lon = 34.833515086455606,
                            Name = "Independence Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 3,
                            Address = "175 Yitzhak Rabin St, Hadera",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.272371856350432,
                            Lon = 35.204065234472438,
                            Name = "Yarkon Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 4,
                            Address = "187 Weizmann St, Herzliya",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.024759260047205,
                            Lon = 35.253395568849179,
                            Name = "Sacher Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 5,
                            Address = "157 Arlozorov St, Bat Yam",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.44664646109781,
                            Lon = 35.289702085201149,
                            Name = "Ramat Gan National Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 6,
                            Address = "85 Dizengoff St, Holon",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.98934153777936,
                            Lon = 35.144770000185744,
                            Name = "HaPisga Garden",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Ben Gurion St, Petah Tikva",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.874967783385415,
                            Lon = 35.13429068828674,
                            Name = "Canada Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 8,
                            Address = "17 Yitzhak Rabin St, Ramat Gan",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.8352893931783,
                            Lon = 34.975209784302109,
                            Name = "Ashdod Yam Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 9,
                            Address = "172 Ben Gurion St, Modiin",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.289338568188249,
                            Lon = 34.953429313160918,
                            Name = "Gan Ha'ir",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 10,
                            Address = "157 King David St, Beer Sheva",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.638309978820317,
                            Lon = 35.042803136769834,
                            Name = "Armon Hanatziv Promenade",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 11,
                            Address = "102 Dizengoff St, Ashkelon",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.71993551127747,
                            Lon = 35.11255321228267,
                            Name = "Liberty Bell Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 12,
                            Address = "144 Menachem Begin St, Tel Aviv",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.665500001487391,
                            Lon = 35.244067453024584,
                            Name = "Lachish Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 13,
                            Address = "34 HaShalom St, Haifa",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.120820094775631,
                            Lon = 35.115563847510714,
                            Name = "Ariel Sharon Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 14,
                            Address = "194 Hagana St, Hadera",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.803551327917347,
                            Lon = 35.379364714028313,
                            Name = "Park Giv'atayim",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 15,
                            Address = "182 Herzl St, Beer Sheva",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.872133215672076,
                            Lon = 34.893645083143596,
                            Name = "Herzliya Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 16,
                            Address = "195 HaShalom St, Kiryat Gat",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.615266362705807,
                            Lon = 35.06257633500924,
                            Name = "Park Ashkelon",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 17,
                            Address = "199 Aharonovitch St, Nazareth",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.101123361846554,
                            Lon = 34.849212007757842,
                            Name = "Beit She'an Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 18,
                            Address = "45 Herzl St, Tiberias",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.890672987049868,
                            Lon = 34.882431927506886,
                            Name = "Ein Gedi Reserve",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 19,
                            Address = "162 Menachem Begin St, Jerusalem",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.28720398697163,
                            Lon = 35.168115053048986,
                            Name = "Neot Kedumim",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 20,
                            Address = "128 Weizmann St, Rehovot",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 32.869487722748907,
                            Lon = 34.927139801670656,
                            Name = "Ma'ayan Harod",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 21,
                            Address = "45 Herzl St, Tiberias",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.510898154436077,
                            Lon = 35.311001392921952,
                            Name = "Timna Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 22,
                            Address = "199 Aharonovitch St, Nazareth",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 31.972501396363768,
                            Lon = 35.332655801144597,
                            Name = "Alona Park",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 23,
                            Address = "143 King David St, Netanya",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.733553750808422,
                            Lon = 35.039765203149045,
                            Name = "Park Kiryat Motzkin",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 24,
                            Address = "162 Menachem Begin St, Jerusalem",
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Beautiful park for dogs. Great for playing and resting.",
                            Lat = 30.881452108674239,
                            Lon = 35.273713371165115,
                            Name = "Bat Galim Promenade",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        });
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 25, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7989),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user1@tail.com",
                            FirstName = "User1",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last1",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1976, 12, 3, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8002),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user2@tail.com",
                            FirstName = "User2",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last2",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 1, 2, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8006),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user3@tail.com",
                            FirstName = "User3",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last3",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1997, 5, 25, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8008),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user4@tail.com",
                            FirstName = "User4",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last4",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 12, 1, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8011),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user5@tail.com",
                            FirstName = "User5",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last5",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2005, 5, 4, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8014),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user6@tail.com",
                            FirstName = "User6",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last6",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1991, 5, 8, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8016),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user7@tail.com",
                            FirstName = "User7",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last7",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1991, 11, 9, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8061),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user8@tail.com",
                            FirstName = "User8",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last8",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1981, 11, 30, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8064),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user9@tail.com",
                            FirstName = "User9",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last9",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1986, 10, 24, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8067),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user10@tail.com",
                            FirstName = "User10",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last10",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2006, 11, 29, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8070),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user11@tail.com",
                            FirstName = "User11",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last11",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1985, 11, 14, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8072),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user12@tail.com",
                            FirstName = "User12",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last12",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1999, 4, 30, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8075),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user13@tail.com",
                            FirstName = "User13",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last13",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1988, 9, 3, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8077),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user14@tail.com",
                            FirstName = "User14",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last14",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1996, 5, 23, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8080),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user15@tail.com",
                            FirstName = "User15",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Last15",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1988, 11, 10, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8083),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user16@tail.com",
                            FirstName = "User16",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last16",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1989, 5, 18, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8085),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user17@tail.com",
                            FirstName = "User17",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last17",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1982, 9, 19, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8088),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user18@tail.com",
                            FirstName = "User18",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last18",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1993, 5, 5, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8091),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user19@tail.com",
                            FirstName = "User19",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Last19",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1987, 3, 18, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(8093),
                            CreatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549),
                            Email = "user20@tail.com",
                            FirstName = "User20",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Last20",
                            UpdatedAt = new DateTime(2025, 4, 20, 21, 0, 1, 312, DateTimeKind.Utc).AddTicks(7549)
                        });
                });

            modelBuilder.Entity("DogParks", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Park", null)
                        .WithMany()
                        .HasForeignKey("FavParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("ChatsAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("ChatsAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.ChatNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("UnreadChatNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("Images")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TailBuddys.Core.Models.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dog");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReceiverDog")
                        .WithMany("MatchesAsReceiver")
                        .HasForeignKey("ReceiverDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("MatchesAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.MatchNotification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("MatchNotification")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Match", "Match")
                        .WithMany("MatchNotification")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Navigation("ChatsAsReceiver");

                    b.Navigation("ChatsAsSender");

                    b.Navigation("Images");

                    b.Navigation("MatchNotification");

                    b.Navigation("MatchesAsReceiver");

                    b.Navigation("MatchesAsSender");

                    b.Navigation("UnreadChatNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Navigation("MatchNotification");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
