// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TailBuddys.Infrastructure.Data;

#nullable disable

namespace TailBuddys.InfraStructure.Migrations
{
    [DbContext(typeof(TailBuddysContext))]
    partial class TailBuddysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogPark", b =>
                {
                    b.Property<string>("DogLikesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FavParksId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DogLikesId", "FavParksId");

                    b.HasIndex("FavParksId");

                    b.ToTable("DogParks", (string)null);
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReciverDogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderDogId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReciverDogId");

                    b.HasIndex("SenderDogId", "ReciverDogId")
                        .IsUnique()
                        .HasFilter("[SenderDogId] IS NOT NULL AND [ReciverDogId] IS NOT NULL");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Geneder")
                        .HasColumnType("bit");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Vaccinated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Images");

                    b.HasDiscriminator<int>("EntityType").HasValue(1);
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<string>("ReciverDogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderDogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReciverDogId");

                    b.HasIndex("SenderDogId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("SenderDogId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatID");

                    b.ToTable("Messeges");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnreadMessages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginDogId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DogPark", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailBuddys.Core.Models.Park", null)
                        .WithMany()
                        .HasForeignKey("FavParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReciverDog")
                        .WithMany("ChatsAsReciver")
                        .HasForeignKey("ReciverDogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("ChatsAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReciverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Image", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("Images")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TailBuddys.Core.Models.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dog");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Match", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "ReciverDog")
                        .WithMany("MatchesAsReciver")
                        .HasForeignKey("ReciverDogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TailBuddys.Core.Models.Dog", "SenderDog")
                        .WithMany("MatchesAsSender")
                        .HasForeignKey("SenderDogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReciverDog");

                    b.Navigation("SenderDog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Message", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Notification", b =>
                {
                    b.HasOne("TailBuddys.Core.Models.Dog", "Dog")
                        .WithMany("Notifications")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Dog", b =>
                {
                    b.Navigation("ChatsAsReciver");

                    b.Navigation("ChatsAsSender");

                    b.Navigation("Images");

                    b.Navigation("MatchesAsReciver");

                    b.Navigation("MatchesAsSender");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.Park", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TailBuddys.Core.Models.User", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
